-- Compact reusable views for Excel Power Query / PivotTables.

DROP VIEW IF EXISTS vw_dashboard_monthly;
CREATE VIEW vw_dashboard_monthly AS
WITH m AS (
 SELECT PERIOD_BEGIN,
   SUM(MEDIAN_SALE_PRICE*HOMES_SOLD)/NULLIF(SUM(HOMES_SOLD),0) AS weighted_median_price,
   SUM(HOMES_SOLD) AS homes_sold,
   SUM(INVENTORY) AS inventory,
   SUM(MONTHS_OF_SUPPLY*INVENTORY)/NULLIF(SUM(INVENTORY),0) AS months_of_supply,
   SUM(MEDIAN_DOM*HOMES_SOLD)/NULLIF(SUM(HOMES_SOLD),0) AS median_dom,
   SUM(CASE WHEN AVG_SALE_TO_LIST BETWEEN 0.5 AND 1.5 THEN AVG_SALE_TO_LIST*HOMES_SOLD END)
     /NULLIF(SUM(CASE WHEN AVG_SALE_TO_LIST BETWEEN 0.5 AND 1.5 THEN HOMES_SOLD END),0) AS sale_to_list_ratio,
   SUM(SOLD_ABOVE_LIST*HOMES_SOLD)/NULLIF(SUM(HOMES_SOLD),0) AS sold_above_list,
   SUM(PRICE_DROPS*INVENTORY)/NULLIF(SUM(INVENTORY),0) AS price_drops
 FROM real_estate_clean
 WHERE PROPERTY_TYPE='All Residential' AND PERIOD_END<='2025-10-31' AND HOMES_SOLD>0
 GROUP BY PERIOD_BEGIN
)
SELECT *,
 weighted_median_price/NULLIF(LAG(weighted_median_price,1) OVER(ORDER BY PERIOD_BEGIN),0)-1 AS price_mom,
 weighted_median_price/NULLIF(LAG(weighted_median_price,12) OVER(ORDER BY PERIOD_BEGIN),0)-1 AS price_yoy,
 AVG(weighted_median_price) OVER(ORDER BY PERIOD_BEGIN ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS rolling_3m_price,
 AVG(weighted_median_price) OVER(ORDER BY PERIOD_BEGIN ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS rolling_12m_price
FROM m;

DROP VIEW IF EXISTS vw_dashboard_state;
CREATE VIEW vw_dashboard_state AS
SELECT STATE_CODE,STATE,SUM(HOMES_SOLD) AS total_homes_sold,
 SUM(MEDIAN_SALE_PRICE*HOMES_SOLD)/NULLIF(SUM(HOMES_SOLD),0) AS weighted_median_price,
 SUM(INVENTORY) AS inventory,
 SUM(MEDIAN_DOM*HOMES_SOLD)/NULLIF(SUM(HOMES_SOLD),0) AS median_dom,
 SUM(CASE WHEN AVG_SALE_TO_LIST BETWEEN 0.5 AND 1.5 THEN AVG_SALE_TO_LIST*HOMES_SOLD END)
   /NULLIF(SUM(CASE WHEN AVG_SALE_TO_LIST BETWEEN 0.5 AND 1.5 THEN HOMES_SOLD END),0) AS sale_to_list_ratio
FROM real_estate_clean
WHERE PROPERTY_TYPE='All Residential' AND PERIOD_END<='2025-10-31' AND HOMES_SOLD>0
GROUP BY STATE_CODE,STATE;

DROP VIEW IF EXISTS vw_dashboard_city_current;
CREATE VIEW vw_dashboard_city_current AS
SELECT REGION,CITY,STATE_CODE,PROPERTY_TYPE,MEDIAN_SALE_PRICE,MEDIAN_SALE_PRICE_YOY,HOMES_SOLD,
 INVENTORY,MONTHS_OF_SUPPLY,MEDIAN_DOM,AVG_SALE_TO_LIST,SOLD_ABOVE_LIST,PRICE_DROPS,PARENT_METRO_REGION,
 CASE WHEN HOMES_SOLD<20 THEN 1 ELSE 0 END AS small_sample_flag,
 CASE WHEN MEDIAN_SALE_PRICE<10000 OR MEDIAN_SALE_PRICE>5000000 THEN 1 ELSE 0 END AS price_outlier_flag
FROM real_estate_clean WHERE PERIOD_BEGIN='2025-10-01';

DROP VIEW IF EXISTS vw_dashboard_property_type;
CREATE VIEW vw_dashboard_property_type AS
SELECT PROPERTY_TYPE,SUM(HOMES_SOLD) AS homes_sold,
 SUM(MEDIAN_SALE_PRICE*HOMES_SOLD)/NULLIF(SUM(HOMES_SOLD),0) AS weighted_median_price
FROM real_estate_clean WHERE PERIOD_END<='2025-10-31' AND HOMES_SOLD>0
GROUP BY PROPERTY_TYPE;

DROP VIEW IF EXISTS vw_dashboard_kpis;
CREATE VIEW vw_dashboard_kpis AS
WITH cur AS (SELECT * FROM vw_dashboard_monthly WHERE PERIOD_BEGIN='2025-10-01'),
common AS (
 SELECT TABLE_ID FROM real_estate_clean
 WHERE PROPERTY_TYPE='All Residential' AND PERIOD_BEGIN IN ('2012-01-01','2025-10-01')
 GROUP BY TABLE_ID HAVING COUNT(DISTINCT PERIOD_BEGIN)=2
), endpoints AS (
 SELECT PERIOD_BEGIN,SUM(MEDIAN_SALE_PRICE*HOMES_SOLD)/SUM(HOMES_SOLD) price
 FROM real_estate_clean JOIN common USING(TABLE_ID)
 WHERE PROPERTY_TYPE='All Residential' AND PERIOD_BEGIN IN ('2012-01-01','2025-10-01') AND HOMES_SOLD>0
 GROUP BY PERIOD_BEGIN
)
SELECT
 (SELECT COUNT(*) FROM real_estate_clean WHERE PERIOD_END<='2025-10-31') AS total_records,
 (SELECT COUNT(DISTINCT REGION) FROM real_estate_clean WHERE PERIOD_END<='2025-10-31') AS city_state_markets,
 (SELECT COUNT(DISTINCT STATE_CODE) FROM real_estate_clean) AS states_and_dc,
 (SELECT SUM(HOMES_SOLD) FROM real_estate_clean WHERE PROPERTY_TYPE='All Residential' AND PERIOD_END<='2025-10-31') AS total_homes_sold,
 cur.weighted_median_price AS current_weighted_price,cur.price_yoy AS latest_yoy,
 cur.median_dom,cur.inventory,cur.sale_to_list_ratio,
 (SELECT MAX(CASE WHEN PERIOD_BEGIN='2025-10-01' THEN price END)/MAX(CASE WHEN PERIOD_BEGIN='2012-01-01' THEN price END)-1 FROM endpoints) AS long_term_growth
FROM cur;

