-- Run after the CSV has been imported into real_estate_raw.
-- Dates in the source are DD-MM-YYYY and are converted to ISO YYYY-MM-DD.

DROP TABLE IF EXISTS real_estate_clean;

CREATE TABLE real_estate_clean AS
WITH normalized AS (
    SELECT
        CASE WHEN PERIOD_BEGIN GLOB '??-??-????'
             THEN substr(PERIOD_BEGIN,7,4)||'-'||substr(PERIOD_BEGIN,4,2)||'-'||substr(PERIOD_BEGIN,1,2) END AS PERIOD_BEGIN,
        CASE WHEN PERIOD_END GLOB '??-??-????'
             THEN substr(PERIOD_END,7,4)||'-'||substr(PERIOD_END,4,2)||'-'||substr(PERIOD_END,1,2) END AS PERIOD_END,
        CAST(NULLIF(TRIM(PERIOD_DURATION),'') AS INTEGER) AS PERIOD_DURATION,
        NULLIF(TRIM(REGION_TYPE),'') AS REGION_TYPE,
        CAST(NULLIF(TRIM(REGION_TYPE_ID),'') AS INTEGER) AS REGION_TYPE_ID,
        CAST(NULLIF(TRIM(TABLE_ID),'') AS INTEGER) AS TABLE_ID,
        CASE UPPER(TRIM(IS_SEASONALLY_ADJUSTED)) WHEN 'TRUE' THEN 1 WHEN 'FALSE' THEN 0 END AS IS_SEASONALLY_ADJUSTED,
        NULLIF(TRIM(REGION),'') AS REGION,
        NULLIF(TRIM(CITY),'') AS CITY,
        NULLIF(TRIM(STATE),'') AS STATE,
        NULLIF(TRIM(STATE_CODE),'') AS STATE_CODE,
        NULLIF(TRIM(PROPERTY_TYPE),'') AS PROPERTY_TYPE,
        CAST(NULLIF(TRIM(PROPERTY_TYPE_ID),'') AS INTEGER) AS PROPERTY_TYPE_ID,
        CAST(NULLIF(TRIM(MEDIAN_SALE_PRICE),'') AS REAL) AS MEDIAN_SALE_PRICE,
        CAST(NULLIF(TRIM(MEDIAN_SALE_PRICE_MOM),'') AS REAL) AS MEDIAN_SALE_PRICE_MOM,
        CAST(NULLIF(TRIM(MEDIAN_SALE_PRICE_YOY),'') AS REAL) AS MEDIAN_SALE_PRICE_YOY,
        CAST(NULLIF(TRIM(MEDIAN_LIST_PRICE),'') AS REAL) AS MEDIAN_LIST_PRICE,
        CAST(NULLIF(TRIM(MEDIAN_LIST_PRICE_MOM),'') AS REAL) AS MEDIAN_LIST_PRICE_MOM,
        CAST(NULLIF(TRIM(MEDIAN_LIST_PRICE_YOY),'') AS REAL) AS MEDIAN_LIST_PRICE_YOY,
        CAST(NULLIF(TRIM(MEDIAN_PPSF),'') AS REAL) AS MEDIAN_PPSF,
        CAST(NULLIF(TRIM(MEDIAN_PPSF_MOM),'') AS REAL) AS MEDIAN_PPSF_MOM,
        CAST(NULLIF(TRIM(MEDIAN_PPSF_YOY),'') AS REAL) AS MEDIAN_PPSF_YOY,
        CAST(NULLIF(TRIM(MEDIAN_LIST_PPSF),'') AS REAL) AS MEDIAN_LIST_PPSF,
        CAST(NULLIF(TRIM(MEDIAN_LIST_PPSF_MOM),'') AS REAL) AS MEDIAN_LIST_PPSF_MOM,
        CAST(NULLIF(TRIM(MEDIAN_LIST_PPSF_YOY),'') AS REAL) AS MEDIAN_LIST_PPSF_YOY,
        CAST(NULLIF(TRIM(HOMES_SOLD),'') AS INTEGER) AS HOMES_SOLD,
        CAST(NULLIF(TRIM(HOMES_SOLD_MOM),'') AS REAL) AS HOMES_SOLD_MOM,
        CAST(NULLIF(TRIM(HOMES_SOLD_YOY),'') AS REAL) AS HOMES_SOLD_YOY,
        CAST(NULLIF(TRIM(PENDING_SALES),'') AS INTEGER) AS PENDING_SALES,
        CAST(NULLIF(TRIM(PENDING_SALES_MOM),'') AS REAL) AS PENDING_SALES_MOM,
        CAST(NULLIF(TRIM(PENDING_SALES_YOY),'') AS REAL) AS PENDING_SALES_YOY,
        CAST(NULLIF(TRIM(NEW_LISTINGS),'') AS INTEGER) AS NEW_LISTINGS,
        CAST(NULLIF(TRIM(NEW_LISTINGS_MOM),'') AS REAL) AS NEW_LISTINGS_MOM,
        CAST(NULLIF(TRIM(NEW_LISTINGS_YOY),'') AS REAL) AS NEW_LISTINGS_YOY,
        CAST(NULLIF(TRIM(INVENTORY),'') AS INTEGER) AS INVENTORY,
        CAST(NULLIF(TRIM(INVENTORY_MOM),'') AS REAL) AS INVENTORY_MOM,
        CAST(NULLIF(TRIM(INVENTORY_YOY),'') AS REAL) AS INVENTORY_YOY,
        CAST(NULLIF(TRIM(MONTHS_OF_SUPPLY),'') AS REAL) AS MONTHS_OF_SUPPLY,
        CAST(NULLIF(TRIM(MONTHS_OF_SUPPLY_MOM),'') AS REAL) AS MONTHS_OF_SUPPLY_MOM,
        CAST(NULLIF(TRIM(MONTHS_OF_SUPPLY_YOY),'') AS REAL) AS MONTHS_OF_SUPPLY_YOY,
        CAST(NULLIF(TRIM(MEDIAN_DOM),'') AS REAL) AS MEDIAN_DOM,
        CAST(NULLIF(TRIM(MEDIAN_DOM_MOM),'') AS REAL) AS MEDIAN_DOM_MOM,
        CAST(NULLIF(TRIM(MEDIAN_DOM_YOY),'') AS REAL) AS MEDIAN_DOM_YOY,
        CAST(NULLIF(TRIM(AVG_SALE_TO_LIST),'') AS REAL) AS AVG_SALE_TO_LIST,
        CAST(NULLIF(TRIM(AVG_SALE_TO_LIST_MOM),'') AS REAL) AS AVG_SALE_TO_LIST_MOM,
        CAST(NULLIF(TRIM(AVG_SALE_TO_LIST_YOY),'') AS REAL) AS AVG_SALE_TO_LIST_YOY,
        CAST(NULLIF(TRIM(SOLD_ABOVE_LIST),'') AS REAL) AS SOLD_ABOVE_LIST,
        CAST(NULLIF(TRIM(SOLD_ABOVE_LIST_MOM),'') AS REAL) AS SOLD_ABOVE_LIST_MOM,
        CAST(NULLIF(TRIM(SOLD_ABOVE_LIST_YOY),'') AS REAL) AS SOLD_ABOVE_LIST_YOY,
        CAST(NULLIF(TRIM(PRICE_DROPS),'') AS REAL) AS PRICE_DROPS,
        CAST(NULLIF(TRIM(PRICE_DROPS_MOM),'') AS REAL) AS PRICE_DROPS_MOM,
        CAST(NULLIF(TRIM(PRICE_DROPS_YOY),'') AS REAL) AS PRICE_DROPS_YOY,
        CAST(NULLIF(TRIM(OFF_MARKET_IN_TWO_WEEKS),'') AS REAL) AS OFF_MARKET_IN_TWO_WEEKS,
        CAST(NULLIF(TRIM(OFF_MARKET_IN_TWO_WEEKS_MOM),'') AS REAL) AS OFF_MARKET_IN_TWO_WEEKS_MOM,
        CAST(NULLIF(TRIM(OFF_MARKET_IN_TWO_WEEKS_YOY),'') AS REAL) AS OFF_MARKET_IN_TWO_WEEKS_YOY,
        NULLIF(TRIM(PARENT_METRO_REGION),'') AS PARENT_METRO_REGION,
        CAST(NULLIF(TRIM(PARENT_METRO_REGION_METRO_CODE),'') AS INTEGER) AS PARENT_METRO_REGION_METRO_CODE,
        NULLIF(TRIM(LAST_UPDATED),'') AS LAST_UPDATED,
        ROW_NUMBER() OVER (
            PARTITION BY TABLE_ID, PERIOD_BEGIN, PROPERTY_TYPE, IS_SEASONALLY_ADJUSTED
            ORDER BY rowid
        ) AS duplicate_sequence
    FROM real_estate_raw
)
SELECT * FROM normalized WHERE duplicate_sequence = 1;

DROP VIEW IF EXISTS data_quality_flags;
CREATE VIEW data_quality_flags AS
SELECT
    TABLE_ID, PERIOD_BEGIN, REGION, PROPERTY_TYPE,
    CASE WHEN PERIOD_BEGIN IS NULL OR PERIOD_END IS NULL THEN 1 ELSE 0 END AS invalid_date_flag,
    CASE WHEN MEDIAN_SALE_PRICE IS NULL THEN 1 ELSE 0 END AS missing_sale_price_flag,
    CASE WHEN HOMES_SOLD IS NULL THEN 1 ELSE 0 END AS missing_homes_sold_flag,
    CASE WHEN MEDIAN_SALE_PRICE < 10000 OR MEDIAN_SALE_PRICE > 5000000 THEN 1 ELSE 0 END AS price_outlier_flag,
    CASE WHEN AVG_SALE_TO_LIST < 0.50 OR AVG_SALE_TO_LIST > 1.50 THEN 1 ELSE 0 END AS sale_to_list_outlier_flag,
    CASE WHEN HOMES_SOLD < 20 THEN 1 ELSE 0 END AS small_sample_flag,
    CASE WHEN PERIOD_END > '2025-10-31' THEN 1 ELSE 0 END AS after_project_cutoff_flag
FROM real_estate_clean;

-- Index the materialized cleaned table once so repeated dashboard queries are fast.
CREATE UNIQUE INDEX IF NOT EXISTS idx_clean_key
    ON real_estate_clean(TABLE_ID, PERIOD_BEGIN, PROPERTY_TYPE, IS_SEASONALLY_ADJUSTED);
CREATE INDEX IF NOT EXISTS idx_clean_period_property ON real_estate_clean(PERIOD_BEGIN, PROPERTY_TYPE);
CREATE INDEX IF NOT EXISTS idx_clean_state_city ON real_estate_clean(STATE_CODE, CITY);
CREATE INDEX IF NOT EXISTS idx_clean_region ON real_estate_clean(REGION);

-- Quality checks.
SELECT COUNT(*) AS cleaned_rows FROM real_estate_clean;
SELECT COUNT(*) AS flagged_rows FROM data_quality_flags
WHERE invalid_date_flag + missing_sale_price_flag + missing_homes_sold_flag + price_outlier_flag + sale_to_list_outlier_flag > 0;
SELECT * FROM data_quality_flags
WHERE price_outlier_flag = 1 OR sale_to_list_outlier_flag = 1
LIMIT 100;
